function(generateLibraryName Path)
    get_filename_component( LibraryName ${Path} NAME )    
    return(PROPAGATE LibraryName)
endfunction()

function (generateStaticNameFromLibraryName LibraryName)
    set(StaticName ${LibraryName}_static)
    return(PROPAGATE StaticName)
endfunction()

function(generateStaticName Path)
    generateLibraryName(${Path})
    generateStaticNameFromLibraryName(${LibraryName})
    return(PROPAGATE StaticName)
endfunction()

function(generateObjectNameFromLibraryName LibraryName)
    set(ObjectName ${LibraryName}_obj)
    return(PROPAGATE ObjectName)
endfunction()

function(generateObjectName Path)
    generateLibraryName(${Path})
    generateObjectNameFromLibraryName(${LibraryName})
    return(PROPAGATE ObjectName)
endfunction()

function (generateExecutableNameFromLibraryName LibraryName)
    set(ExecutableName ${LibraryName}_exe)
    return(PROPAGATE ExecutableName)
endfunction()

function(generateExecutableName Path)
    generateLibraryName(${Path})
    generateExecutableNameFromLibraryName(${LibraryName})
    return(PROPAGATE ExecutableName)
endfunction()

function(generateTestNameFromLibraryName Path)
    generateLibraryName(${Path})
    set(TestName ${LibraryName}_test)
    return(PROPAGATE TestName)
endfunction()

function(generateTestName Path)
    generateLibraryName(${Path})
    generateTestNameFromLibraryName(${LibraryName})
    return(PROPAGATE TestName)
endfunction()
